-- MySQL Script generated by MySQL Workbench
-- Mon Jun 16 01:06:27 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_desafio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_desafio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_desafio` DEFAULT CHARACTER SET utf8 ;
USE `db_desafio` ;

-- -----------------------------------------------------
-- Table `db_desafio`.`TB_PAUTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_desafio`.`TB_PAUTA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(90) NOT NULL,
  `DESCRICAO` LONGTEXT NOT NULL,
  `DT_CRIACAO` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_desafio`.`TB_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_desafio`.`TB_USUARIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(90) NOT NULL,
  `DT_CRIACAO` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_desafio`.`TB_VOTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_desafio`.`TB_VOTO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TB_PAUTA_ID` INT NOT NULL,
  `TB_USUARIO_ID` INT NOT NULL,
  `DT_CRIACAO` TIMESTAMP NOT NULL,
  `VOTO` ENUM('SIM', 'NÃO') NOT NULL,
  PRIMARY KEY (`ID`, `TB_PAUTA_ID`, `TB_USUARIO_ID`),
  INDEX `fk_TB_VOTO_TB_PAUTA_idx` (`TB_PAUTA_ID` ASC) ,
  INDEX `fk_TB_VOTO_TB_USUARIO1_idx` (`TB_USUARIO_ID` ASC) ,
  CONSTRAINT `fk_TB_VOTO_TB_PAUTA`
    FOREIGN KEY (`TB_PAUTA_ID`)
    REFERENCES `db_desafio`.`TB_PAUTA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_VOTO_TB_USUARIO1`
    FOREIGN KEY (`TB_USUARIO_ID`)
    REFERENCES `db_desafio`.`TB_USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_desafio`.`TB_VOTACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_desafio`.`TB_SESSAO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DT_VOTACAO_INICIADA` TIMESTAMP NULL,
  `DT_VOTACAO_ENCERRADA` TIMESTAMP NULL,
  `TB_PAUTA_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `TB_PAUTA_ID`),
  INDEX `fk_TB_VOTACAO_TB_PAUTA1_idx` (`TB_PAUTA_ID` ASC) ,
  CONSTRAINT `fk_TB_VOTACAO_TB_PAUTA1`
    FOREIGN KEY (`TB_PAUTA_ID`)
    REFERENCES `db_desafio`.`TB_PAUTA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE TB_VOTO
ADD CONSTRAINT UNIQUE_VOTO_POR_PAUTA
UNIQUE (TB_PAUTA_ID, TB_USUARIO_ID);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
